### ISSUE TITLE
Glagolitic Script

### ISSUE THREAD

**Issue by StefanPeev** [krksgbr/glyphcollector#11]
Does Glyph Collector work for any kind of manuscripts? I try to use it for Glagolitic script but it can't collect glyphs on my system - Windows 8.1, Glyph Collector 0.2.2. After the operation Collect Glyphs it shows nothing.

**Comment by krksgbr** [comment]
Hey Stefan. Ironically GlyphCollector doesn't know what glyphs are, it only sees pixel patterns. It doesn't matter what kind of scripts are supplied as input as long as pixel patterns can be correlated.
So it should work with the Glagolitic script. Sometimes the matching algorithm is too strict and rejects candidates that may be valid. I'll make this strictness adjustable through the UI in a new release sometime soon.
In the meantime, if you can send me examples of the material you're using, I can try and see if I can get some results out of it. Sometimes it helps to try with different samples of the same glyph.

**Comment by StefanPeev** [comment]
Thank you for your reply. I send you 2 images. If you need more images or information - let me know.

![uni2C41_Assemani](https://user-images.githubusercontent.com/12949369/77955531-01aff580-72d9-11ea-97b7-4f03b0cfb993.jpg)

![d64bd960-ec08-465f-9242-c783cc4b1cbd](https://user-images.githubusercontent.com/12949369/77955660-3f148300-72d9-11ea-9476-2be46a79cce4.jpg)

**Comment by krksgbr** [comment]
Thanks! Do you have the scan in higher resolution? Could you perhaps send it to me to krks.gbr@gmail.com ? Thanks!
